lib/jibber_web/router.ex
defmodule JibberWeb.Router do
  use JibberWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug Phoenix.LiveView.Flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :authed do
    plug JibberWeb.BasicAuth
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", JibberWeb do
    pipe_through :browser

    scope "/chat" do
      pipe_through [:authed]

      get "/", PageController, :index
    end

    resources "/login", SessionController, singleton: true, only: [:show, :create]
  end

  scope "/", JibberWeb do
    pipe_through :api

    resources "/messages", ChatController, only: [:create]
  end

  # Other scopes may use custom stacks.
  # scope "/api", JibberWeb do
  #   pipe_through :api
  # end
end

lib/jibber/account.ex
defmodule Jibber.Account do
  use Norm
  import Ecto.Query
  alias Jibber.Repo
  alias Jibber.Account.User

  @contract login(name :: spec(is_binary())) :: User.s()
  def login(name) do
    case Repo.get_by(User, name: name) do
      %{id: _} = user ->
        user

      _ ->
        User.changeset(%User{}, %{name: name})
        |> Repo.insert!()
    end
  end

  @contract find_user(user_id :: id_spec()) :: one_of([User.s(), nil])
  def find_user(user_id) do
    Repo.get(User, user_id)
  end

  @contract list_users(param :: one_of([coll_of(id_spec()), spec(is_binary())])) ::
              coll_of(User.s())
  def list_users(param), do: do_list_users(param)

  defp do_list_users(ids) when is_list(ids) do
    query = from(u in User, where: u.id in ^ids)

    Repo.all(query)
  end

  defp do_list_users(name) do
    query = from(u in User, where: like(u.name, ^"%#{name}%"))

    Repo.all(query)
  end

  defp id_spec do
    spec(is_integer() and (&(&1 > 0)))
  end
end

lib/jibber/account/user.ex
defmodule Jibber.Account.User do
  use Norm
  use Ecto.Schema
  import Ecto.Changeset

  schema "users" do
    field :name, :string
    timestamps()
  end

  def changeset(user, params) do
    user
    |> cast(params, [:name])
    |> validate_required(:name)
  end

  def s() do
    schema(%{
      user:
        schema(%{
          name: spec(is_binary())
        })
    })
  end
end

lib/jibber/application.ex
defmodule Jibber.Application do
  # See https://hexdocs.pm/elixir/Application.html
  # for more information on OTP Applications
  @moduledoc false

  use Application

  def start(_type, _args) do
    # List all child processes to be supervised
    children = [
      # Start the Ecto repository
      Jibber.Repo,
      # Start the endpoint when the application starts
      JibberWeb.Endpoint
      # Starts a worker by calling: Jibber.Worker.start_link(arg)
      # {Jibber.Worker, arg},
    ]

    # See https://hexdocs.pm/elixir/Supervisor.html
    # for other strategies and supported options
    opts = [strategy: :one_for_one, name: Jibber.Supervisor]
    Supervisor.start_link(children, opts)
  end

  # Tell Phoenix to update the endpoint configuration
  # whenever the application is updated.
  def config_change(changed, _new, removed) do
    JibberWeb.Endpoint.config_change(changed, removed)
    :ok
  end
end

lib/jibber/chat.ex
defmodule Jibber.Chat do
  use Norm
  import Ecto.Query
  alias Jibber.Repo
  alias Jibber.Chat.{Room, Message}

  def list_rooms(user_id) do
    query = from(r in Room, where: ^user_id in r.user_ids)

    {:ok, Repo.all(query)}
  end

  def list_messages(room_id) do
    query = from(m in Message, where: ^room_id == m.room_id)

    Repo.all(query)
  end

  def create_message(room_id, user_id, content) do
    %Message{room_id: room_id, user_id: user_id}
    |> Message.changeset(%{content: content})
    |> Repo.insert()
  end
end

lib/jibber/chat/message.ex
defmodule Jibber.Chat.Message do
  use Norm
  use Ecto.Schema
  import Ecto.Changeset
  alias Jibber.Chat.Room

  schema "messages" do
    field :content, :string
    field :user_id, :integer

    belongs_to :room, Room
    timestamps()
  end

  def changeset(message, params) do
    message
    |> cast(params, [:content])
    |> foreign_key_constraint(:room_id)
    |> foreign_key_constraint(:user_id)
  end
end

lib/jibber/chat/room.ex
defmodule Jibber.Chat.Room do
  use Norm
  use Ecto.Schema

  schema "rooms" do
    field :user_ids, {:array, :integer}

    has_many :messages, Jibber.Chat.Message
    timestamps()
  end
end

lib/jibber/reaction/reaction.ex
defmodule Jibber.Reaction do
end

lib/jibber/repo.ex
defmodule Jibber.Repo do
  use Ecto.Repo,
    otp_app: :jibber,
    adapter: Ecto.Adapters.Postgres
end

lib/jibber_web/controllers/chat_controller.ex
defmodule JibberWeb.ChatController do
  use JibberWeb, :controller

  def create(conn, %{"message" => msg}) do
    text(conn, "echo: " <> msg)
  end
end

lib/jibber_web/controllers/page_controller.ex
defmodule JibberWeb.PageController do
  use JibberWeb, :controller

  def index(conn, _params) do
    %{name: name} = get_session(conn, :current_user)
    render(conn, "chat.html", username: name)
  end
end

lib/jibber_web/controllers/session_controller.ex
defmodule JibberWeb.SessionController do
  use JibberWeb, :controller

  alias Jibber.Account

  plug :put_view, JibberWeb.SessionView

  def show(conn, _params) do
    render(conn, "login.html")
  end

  def create(conn, %{"user" => %{"name" => user_name}}) do
    user = Account.login(user_name)

    conn
    |> put_session(:current_user, user)
    |> redirect(to: "/chat")
  end
end

lib/jibber_web/lives/chat/conversation_live.ex
defmodule JibberWeb.Chat.ConversationLive do
  use Phoenix.LiveView

  alias Jibber.Chat
  alias JibberWeb.ChatView

  @default_assign %{messages: []}

  def render(assigns),
    do: ChatView.render("chat_panel/conversation.html", assigns)

  def mount(session, socket) do
    %{"room_id" => room_id} = session
    if connected?(socket), do: Phoenix.PubSub.subscribe(Jibber.PubSub, "chat:#{room_id}")
    send(self(), {:load_messages, room_id})
    {:ok, assign(socket, @default_assign)}
  end

  def handle_info({:load_messages, room_id}, socket) do
    messages = Chat.list_messages(room_id)
    {:noreply, assign(socket, messages: messages)}
  end

  def handle_info({:new_msg, msg}, socket) do
    %{messages: msgs} = socket.assigns
    {:noreply, assign(socket, messages: msgs ++ [msg])}
  end
end

lib/jibber_web/lives/chat/input_live.ex
defmodule JibberWeb.Chat.InputLive do
  use Phoenix.LiveView

  alias JibberWeb.ChatView

  def render(assigns), do: ChatView.render("chat_panel/input.html", assigns)

  def mount(session, socket) do
    %{"username" => username, "room_id" => room_id} = session
    assigns = %{input_text: nil, username: username, room_id: room_id}
    {:ok, assign(socket, assigns)}
  end

  def handle_info(:clear_input, socket) do
    {:noreply, assign(socket, :input_text, nil)}
  end

  def handle_event("send-message", val, socket) do
    %{assigns: %{room_id: room_id}} = socket

    case Jibber.Chat.create_message(room_id, 1, val["message"]) do
      {:ok, msg} -> Phoenix.PubSub.broadcast(Jibber.PubSub, "chat:#{room_id}", {:new_msg, msg})
      error -> error
    end

    send(self(), :clear_input)

    {:noreply, assign(socket, :input_text, "")}
  end
end

lib/jibber_web/lives/sidebar/search_live.ex
defmodule JibberWeb.Sidebar.SearchLive do
  use Phoenix.LiveView
  alias JibberWeb.ChatView

  def render(assigns),
    do: ChatView.render("user_sidebar/search.html", assigns)

  # def mount(session, socket) do
  # end

  # def handle_info({}, socket) do
  # end
end

lib/jibber_web/views/chat_view.ex
defmodule JibberWeb.ChatView do
  use JibberWeb, :view
end

lib/jibber_web/views/error_view.ex
defmodule JibberWeb.ErrorView do
  use JibberWeb, :view

  # If you want to customize a particular status code
  # for a certain format, you may uncomment below.
  # def render("500.html", _assigns) do
  #   "Internal Server Error"
  # end

  # By default, Phoenix returns the status message from
  # the template name. For example, "404.html" becomes
  # "Not Found".
  def template_not_found(template, _assigns) do
    Phoenix.Controller.status_message_from_template(template)
  end
end

lib/jibber_web/views/layout_view.ex
defmodule JibberWeb.LayoutView do
  use JibberWeb, :view
end

lib/jibber_web/views/page_view.ex
defmodule JibberWeb.PageView do
  use JibberWeb, :view

  alias JibberWeb.ChatView
end

lib/jibber_web/views/session_view.ex
defmodule JibberWeb.SessionView do
  use JibberWeb, :view
end

lib/jibber_web/templates/chat/chat_panel.html.eex
<!-- Right -->
<div class="w-2/3 border flex flex-col">

  <%= render "chat_panel/header.html" %>

  <!-- Messages -->
  <div class="flex-1 overflow-auto" style="background-color: #DAD3CC" >
    <%= live_render @conn, JibberWeb.Chat.ConversationLive,
          session: %{"room_id" => 1},
          container: {:div, class: "py-2 px-3"}
    %>
  </div>

  <!-- Input -->
  <%= live_render @conn, JibberWeb.Chat.InputLive,
        session: %{"username" => @username, "room_id" => 1},
        container: {:div, class: "bg-grey-lighter px-4 py-4 flex items-center"}
  %>

</div>

lib/jibber_web/templates/chat/chat_panel/conversation.html.leex
<div phx-hook="ConversationPanel">
  <div class="flex justify-center mb-2">
    <div class="rounded py-2 px-4" style="background-color: #DDECF2">
      <p class="text-sm uppercase">
        February 20, 2018
      </p>
    </div>
  </div>

  <div class="flex justify-center mb-4">
    <div class="rounded py-2 px-4" style="background-color: #FCF4CB">
      <p class="text-xs">
        Messages to this chat and calls are now secured with end-to-end encryption. Tap for more info.
      </p>
    </div>
  </div>

  <div class="flex mb-2">
    <div class="rounded py-2 px-3" style="background-color: #F2F2F2">
      <p class="text-sm text-teal">
        Sylverter Stallone
      </p>
      <p class="text-sm mt-1">
        Hi everyone! Glad you could join! I am making a new movie.
      </p>
      <p class="text-right text-xs text-grey-dark mt-1">
        12:45 pm
      </p>
    </div>
  </div>

  <div class="flex mb-2">
    <div class="rounded py-2 px-3" style="background-color: #F2F2F2">
      <p class="text-sm text-purple">
        Tom Cruise
      </p>
      <p class="text-sm mt-1">
        Hi all! I have one question for the movie
      </p>
      <p class="text-right text-xs text-grey-dark mt-1">
        12:45 pm
      </p>
    </div>
  </div>

  <div class="flex mb-2">
    <div class="rounded py-2 px-3" style="background-color: #F2F2F2">
      <p class="text-sm text-orange">
        Harrison Ford
      </p>
      <p class="text-sm mt-1">
        Again?
      </p>
      <p class="text-right text-xs text-grey-dark mt-1">
        12:45 pm
      </p>
    </div>
  </div>

  <div class="flex mb-2">
    <div class="rounded py-2 px-3" style="background-color: #F2F2F2">
      <p class="text-sm text-orange">
        Russell Crowe
      </p>
      <p class="text-sm mt-1">
        Is Andrés coming for this one?
      </p>
      <p class="text-right text-xs text-grey-dark mt-1">
        12:45 pm
      </p>
    </div>
  </div>

  <div class="flex mb-2">
    <div class="rounded py-2 px-3" style="background-color: #F2F2F2">
      <p class="text-sm text-teal">
        Sylverter Stallone
      </p>
      <p class="text-sm mt-1">
        He is. Just invited him to join.
      </p>
      <p class="text-right text-xs text-grey-dark mt-1">
        12:45 pm
      </p>
    </div>
  </div>

  <div class="flex justify-end mb-2">
    <div class="rounded py-2 px-3" style="background-color: #E2F7CB">
      <p class="text-sm mt-1">
        Hi guys.
      </p>
      <p class="text-right text-xs text-grey-dark mt-1">
        12:45 pm
      </p>
    </div>
  </div>

  <div class="flex justify-end mb-2">
    <div class="rounded py-2 px-3" style="background-color: #E2F7CB">
      <p class="text-sm mt-1">
        Count me in
      </p>
      <p class="text-right text-xs text-grey-dark mt-1">
        12:45 pm
      </p>
    </div>
  </div>

  <div class="flex mb-2">
    <div class="rounded py-2 px-3" style="background-color: #F2F2F2">
      <p class="text-sm text-purple">
        Tom Cruise
      </p>
      <p class="text-sm mt-1">
        Get Andrés on this movie ASAP!
      </p>
      <p class="text-right text-xs text-grey-dark mt-1">
        12:45 pm
      </p>
    </div>
  </div>

  <%= for msg <- @messages do %>
    <div class="flex justify-end mb-2">
      <div class="rounded py-2 px-3" style="background-color: #E2F7CB">
        <p class="text-sm mt-1">
          <%= msg.content %>
        </p>
        <p class="text-right text-xs text-grey-dark mt-1">
          <%= msg.inserted_at %>
        </p>
      </div>
    </div>
  <% end %>
</div>

lib/jibber_web/templates/chat/chat_panel/header.html.eex
<!-- Header -->
<div class="py-2 px-3 bg-grey-lighter flex flex-row justify-between items-center">
  <div class="flex items-center">
    <div class="ml-4">
      <p class="text-grey-darkest">
        New Movie! Expendables 4
      </p>
      <p class="text-grey-darker text-xs mt-1">
        Andrés, Tom, Harrison, Arnold, Sylvester
      </p>
    </div>
  </div>

  <div class="flex">
    <div>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="#263238" fill-opacity=".5" d="M15.9 14.3H15l-.3-.3c1-1.1 1.6-2.7 1.6-4.3 0-3.7-3-6.7-6.7-6.7S3 6 3 9.7s3 6.7 6.7 6.7c1.6 0 3.2-.6 4.3-1.6l.3.3v.8l5.1 5.1 1.5-1.5-5-5.2zm-6.2 0c-2.6 0-4.6-2.1-4.6-4.6s2.1-4.6 4.6-4.6 4.6 2.1 4.6 4.6-2 4.6-4.6 4.6z"></path></svg>
    </div>
    <div class="ml-6">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="#263238" fill-opacity=".5" d="M1.816 15.556v.002c0 1.502.584 2.912 1.646 3.972s2.472 1.647 3.974 1.647a5.58 5.58 0 0 0 3.972-1.645l9.547-9.548c.769-.768 1.147-1.767 1.058-2.817-.079-.968-.548-1.927-1.319-2.698-1.594-1.592-4.068-1.711-5.517-.262l-7.916 7.915c-.881.881-.792 2.25.214 3.261.959.958 2.423 1.053 3.263.215l5.511-5.512c.28-.28.267-.722.053-.936l-.244-.244c-.191-.191-.567-.349-.957.04l-5.506 5.506c-.18.18-.635.127-.976-.214-.098-.097-.576-.613-.213-.973l7.915-7.917c.818-.817 2.267-.699 3.23.262.5.501.802 1.1.849 1.685.051.573-.156 1.111-.589 1.543l-9.547 9.549a3.97 3.97 0 0 1-2.829 1.171 3.975 3.975 0 0 1-2.83-1.173 3.973 3.973 0 0 1-1.172-2.828c0-1.071.415-2.076 1.172-2.83l7.209-7.211c.157-.157.264-.579.028-.814L11.5 4.36a.572.572 0 0 0-.834.018l-7.205 7.207a5.577 5.577 0 0 0-1.645 3.971z"></path></svg>
    </div>
    <div class="ml-6">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="#263238" fill-opacity=".6" d="M12 7a2 2 0 1 0-.001-4.001A2 2 0 0 0 12 7zm0 2a2 2 0 1 0-.001 3.999A2 2 0 0 0 12 9zm0 6a2 2 0 1 0-.001 3.999A2 2 0 0 0 12 15z"></path></svg>
    </div>
  </div>
</div>

lib/jibber_web/templates/chat/chat_panel/input.html.leex
<div>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path opacity=".45" fill="#263238" d="M9.153 11.603c.795 0 1.439-.879 1.439-1.962s-.644-1.962-1.439-1.962-1.439.879-1.439 1.962.644 1.962 1.439 1.962zm-3.204 1.362c-.026-.307-.131 5.218 6.063 5.551 6.066-.25 6.066-5.551 6.066-5.551-6.078 1.416-12.129 0-12.129 0zm11.363 1.108s-.669 1.959-5.051 1.959c-3.505 0-5.388-1.164-5.607-1.959 0 0 5.912 1.055 10.658 0zM11.804 1.011C5.609 1.011.978 6.033.978 12.228s4.826 10.761 11.021 10.761S23.02 18.423 23.02 12.228c.001-6.195-5.021-11.217-11.216-11.217zM12 21.354c-5.273 0-9.381-3.886-9.381-9.159s3.942-9.548 9.215-9.548 9.548 4.275 9.548 9.548c-.001 5.272-4.109 9.159-9.382 9.159zm3.108-9.751c.795 0 1.439-.879 1.439-1.962s-.644-1.962-1.439-1.962-1.439.879-1.439 1.962.644 1.962 1.439 1.962z"></path></svg>
</div>
<div class="flex-1 mx-4">
  <form phx-submit="send-message">
    <input class="w-full border rounded px-2 py-2" type="text" name="message" value="<%= @input_text %>" autofocus />
  </form>
</div>
<div>
  <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="#263238" fill-opacity=".45" d="M11.999 14.942c2.001 0 3.531-1.53 3.531-3.531V4.35c0-2.001-1.53-3.531-3.531-3.531S8.469 2.35 8.469 4.35v7.061c0 2.001 1.53 3.531 3.53 3.531zm6.238-3.53c0 3.531-2.942 6.002-6.237 6.002s-6.237-2.471-6.237-6.002H3.761c0 4.001 3.178 7.297 7.061 7.885v3.884h2.354v-3.884c3.884-.588 7.061-3.884 7.061-7.885h-2z"></path></svg>
</div>

lib/jibber_web/templates/chat/user_sidebar.html.eex
<!-- Left -->
<div class="w-1/3 border flex flex-col">

  <!-- Header -->
  <%= render "user_sidebar/sidebar_header.html", %{} %>

  <!-- Search -->
  <%= live_render @conn, JibberWeb.Sidebar.SearchLive %>

  <!-- Contacts -->
  <div class="bg-grey-lighter flex-1 overflow-auto">
    <div class="px-3 flex items-center bg-grey-light cursor-pointer">
      <div class="ml-4 flex-1 border-b border-grey-lighter py-4">
        <div class="flex items-bottom justify-between">
          <p class="text-grey-darkest">
            New Movie! Expendables 4
          </p>
          <p class="text-xs text-grey-darkest">
            12:45 pm
          </p>
        </div>
        <p class="text-grey-dark mt-1 text-sm">
          Get Andrés on this movie ASAP!
        </p>
      </div>
    </div>

    <%= render_many 0..3, __MODULE__, "user_sidebar/sidebar_user_panel.html" %>

  </div>

</div>

lib/jibber_web/templates/chat/user_sidebar/search.html.leex
<div class="py-2 px-2 bg-grey-lightest">
  <input type="text" class="w-full px-2 py-2 text-sm" placeholder="Search or start new chat"/>
</div>

lib/jibber_web/templates/chat/user_sidebar/sidebar_header.html.eex
<div class="py-2 px-3 h-16 bg-grey-lighter flex flex-row justify-between items-center">
  <div class="flex">
    <div>
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="#727A7E" d="M12 20.664a9.163 9.163 0 0 1-6.521-2.702.977.977 0 0 1 1.381-1.381 7.269 7.269 0 0 0 10.024.244.977.977 0 0 1 1.313 1.445A9.192 9.192 0 0 1 12 20.664zm7.965-6.112a.977.977 0 0 1-.944-1.229 7.26 7.26 0 0 0-4.8-8.804.977.977 0 0 1 .594-1.86 9.212 9.212 0 0 1 6.092 11.169.976.976 0 0 1-.942.724zm-16.025-.39a.977.977 0 0 1-.953-.769 9.21 9.21 0 0 1 6.626-10.86.975.975 0 1 1 .52 1.882l-.015.004a7.259 7.259 0 0 0-5.223 8.558.978.978 0 0 1-.955 1.185z"></path></svg>
    </div>
    <div class="ml-4">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path opacity=".55" fill="#263238" d="M19.005 3.175H4.674C3.642 3.175 3 3.789 3 4.821V21.02l3.544-3.514h12.461c1.033 0 2.064-1.06 2.064-2.093V4.821c-.001-1.032-1.032-1.646-2.064-1.646zm-4.989 9.869H7.041V11.1h6.975v1.944zm3-4H7.041V7.1h9.975v1.944z"></path></svg>
    </div>
    <div class="ml-4">
      <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" width="24" height="24"><path fill="#263238" fill-opacity=".6" d="M12 7a2 2 0 1 0-.001-4.001A2 2 0 0 0 12 7zm0 2a2 2 0 1 0-.001 3.999A2 2 0 0 0 12 9zm0 6a2 2 0 1 0-.001 3.999A2 2 0 0 0 12 15z"></path></svg>
    </div>
  </div>
</div>

lib/jibber_web/templates/chat/user_sidebar/sidebar_user_panel.html.eex
<div class="bg-white px-3 flex items-center hover:bg-grey-lighter cursor-pointer">
  <div class="ml-4 flex-1 border-b border-grey-lighter py-4">
    <div class="flex items-bottom justify-between">
      <p class="text-grey-darkest">
        Arnold Schwarzenegger
      </p>
      <p class="text-xs text-grey-darkest">
        12:45 pm
      </p>
    </div>
    <p class="text-grey-dark mt-1 text-sm">
      I'll be back
    </p>
  </div>
</div>

lib/jibber_web/templates/layout/app.html.eex
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
    <title>Jibber · Phoenix Framework</title>
    <link rel="stylesheet" href="<%= Routes.static_path(@conn, "/css/app.css") %>"/>
    <%= csrf_meta_tag() %>
  </head>
  <body class="h-screen flex items-center justify-center bg-gray-400 overflow-hidden">
    <%= render @view_module, @view_template, assigns %>

    <script type="text/javascript" src="<%= Routes.static_path(@conn, "/js/app.js") %>"></script>
  </body>
</html>

lib/jibber_web/templates/page/chat.html.eex
<div>
  <div class="container mx-auto">
    <div class="h-screen bg-gray-200">
      <div class="flex border border-grey rounded shadow-lg h-full">
        <%= render ChatView, "user_sidebar.html", conn: @conn %>
        <%= render ChatView, "chat_panel.html", conn: @conn, username: @username %>
      </div>
    </div>
  </div>
</div>

lib/jibber_web/templates/page/index.html.eex
<section class="phx-hero">
  <h1><%= gettext "Welcome to %{name}!", name: "Phoenix" %></h1>
  <p>A productive web framework that<br/>does not compromise speed or maintainability.</p>
</section>

<section class="row">
  <article class="column">
    <h2>Resources</h2>
    <ul>
      <li>
        <a href="https://hexdocs.pm/phoenix/overview.html">Guides &amp; Docs</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix">Source</a>
      </li>
      <li>
        <a href="https://github.com/phoenixframework/phoenix/blob/v1.4/CHANGELOG.md">v1.4 Changelog</a>
      </li>
    </ul>
  </article>
  <article class="column">
    <h2>Help</h2>
    <ul>
      <li>
        <a href="https://elixirforum.com/c/phoenix-forum">Forum</a>
      </li>
      <li>
        <a href="https://webchat.freenode.net/?channels=elixir-lang">#elixir-lang on Freenode IRC</a>
      </li>
      <li>
        <a href="https://twitter.com/elixirphoenix">Twitter @elixirphoenix</a>
      </li>
    </ul>
  </article>
</section>

lib/jibber_web/templates/session/login.html.eex
<div class="min-h-screen bg-gray-50 flex flex-col justify-center py-12 sm:px-6 lg:px-8">
  <div class="sm:mx-auto sm:w-full sm:max-w-md">
    <h2 class="mt-6 text-center text-3xl leading-9 font-extrabold text-gray-900">
      Who Are You?
    </h2>
  </div>

  <div class="mt-8 sm:mx-auto sm:w-full sm:max-w-md">
    <div class="bg-white py-8 px-4 shadow sm:rounded-lg sm:px-10">
      <%= form_for @conn, Routes.session_path(@conn, :create), fn f -> %>
        <div>
          <div class="mt-1 rounded-md shadow-sm">
            <input id="user_name" type="text" name="user[name]" required class="appearance-none block w-full px-3 py-2 border border-gray-300 rounded-md placeholder-gray-400 focus:outline-none focus:shadow-outline-blue focus:border-blue-300 transition duration-150 ease-in-out sm:text-sm sm:leading-5" placeholder="Your Name"/>
          </div>
        </div>

        <div class="mt-6">
          <span class="block w-full rounded-md shadow-sm">
            <button type="submit" class="w-full flex justify-center py-2 px-4 border border-transparent text-sm font-medium rounded-md text-white bg-indigo-600 hover:bg-indigo-500 focus:outline-none focus:border-indigo-700 focus:shadow-outline-indigo active:bg-indigo-700 transition duration-150 ease-in-out">
              Sign in
            </button>
          </span>
        </div>
      <% end %>
    </div>
  </div>
</div>